sonar.projectKey=swe-bitbybit-project_MVP-frontend
sonar.organization=swe-bitbybit
sonar.projectName=swe-bitbybit-project_MVP-frontend
sonar.sources=lib
sonar.tests=test
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,android/**,ios/**,build/**
sonar.dart.lcov.reportPaths=coverage/lcov.info