# Podfile standard per Flutter (Ottimizzato per GitHub Actions)
platform :ios, '13.0'

# Carica il percorso di Flutter (usando la variabile d'ambiente o Generated.xcconfig)
def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  if File.exist?(generated_xcode_build_settings_path)
    File.foreach(generated_xcode_build_settings_path) do |line|
      matches = line.match(/\AFLUTTER_ROOT=(.*)\z/)
      return matches[1].strip if matches
    end
  end
  ENV['FLUTTER_ROOT']
end

# Importa le macro di Flutter
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

# Configurazione Target
target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.expand_path(File.join('..'), __FILE__)
end

# Fix per i target delle dipendenze
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
