sonar.projectKey=swe-bitbybit_project_MVP-backend
sonar.organization=swe-bitbybit
sonar.projectName=swe-bitbybit_project_MVP-backend
sonar.sources=src
sonar.tests=tests/unit
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=pytest.xml
sonar.exclusions=venv/**,**/__pycache__/**
sonar.coverage.exclusions=tests/integration/*