AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  This is the template for the deploy of the lambda used for app: "L'app che
  protegge e trasforma"

Globals:
  Function:
    Timeout: 10
    Runtime: python3.12
    LoggingConfig:
      LogFormat: JSON

Resources:
  # --- API Gateway ---
  AppHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: app-protegge-trasforma-api-mvp
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - GET
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - Authorization

  # --- DIARY ---
  DiaryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/diary/
      Handler: app.lambda_handler
      FunctionName: lambda-diary-notes-microservice-mvp
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LambdaDynamo-lambda-diary-mvp"

  # --- TRUSTED CONTACTS ---
  TrustedContactFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/trusted_contact/
      Handler: app.lambda_handler
      FunctionName: lambda-trusted-contact-microservice-mvp
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LambdaDynamo-lambda-trusted-con\
        tact-mvp"

  TrustedContactsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Delete
    Properties:
      TableName: trusted-contacts-mvp
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: contact_id
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: contact_id
          AttributeType: S
      SSESpecification:
        SSEEnabled: true

  # --- MATERIALS ---
  GetMaterialsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/materials/
      Handler: lambda_handler.lambda_handler
      FunctionName: fetch-materials-mvp
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LambdaDynamo-http-notes-poc3"
      Events:
        GetMaterials:
          Type: HttpApi
          Properties:
            Path: /materials
            Method: get
            ApiId: !Ref AppHttpApi

  MaterialsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: app-protegge-trasforma-materials-mvp
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # --- SAFE PLACES ---
  GetSafePlacesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/safe_places/
      Handler: lambda_handler.lambda_handler
      FunctionName: fetch-safe-places-mvp
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LambdaDynamo-http-notes-poc3"
      Events:
        GetSafePlaces:
          Type: HttpApi
          Properties:
            Path: /safe-places
            Method: get
            ApiId: !Ref AppHttpApi

  SafePlacesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: app-protegge-trasforma-luoghi-sicuri-mvp
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  ApiUrl:
    Description: "URL base dell'API da inserire nel file .env del frontend"
    Value: !Sub "https://${AppHttpApi}.execute-api.${AWS::Region}.amazonaws.com"

  DiaryFunction:
    Description: Trusted contacts lambda function ARN
    Value: !GetAtt DiaryFunction.Arn

  TrustedContactFunction:
    Description: Diary notes lambda function ARN
    Value: !GetAtt TrustedContactFunction.Arn

  TrustedContactsTable:
    Description: DynamoDB Table Name
    Value: !Ref TrustedContactsTable
