AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  This is the template for the deploy of the lambda used for app: "L'app che
  protegge e trasforma"

Parameters:
  CognitoIssuer:
    Type: String
    Default: "https://cognito-idp.eu-north-1.amazonaws.com/eu-north-1_Vf1MMfPoO"
  CognitoAudience:
    Type: String
    Default: "5dlcoa478c3uve9bctpopae4kl"
  
Globals:
  Function:
    Timeout: 10
    Runtime: python3.12
    LoggingConfig:
      LogFormat: JSON

Resources:
# --- API Gateway ---
  AppHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: app-protegge-trasforma-api-mvp
      Auth:
        DefaultAuthorizer: MyJWTAuthorizer
        Authorizers:
          MyJWTAuthorizer:
            JwtConfiguration:
              Issuer: !Ref CognitoIssuer
              Audience:
                - !Ref CognitoAudience
            IdentitySource: "$request.header.Authorization"
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - Authorization

  DiaryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/diary/
      Handler: app.lambda_handler
      FunctionName: lambda-diary-notes-microservice-mvp
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LambdaDynamo-lambda-diary-mvp"
  
  TrustedContactFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/trusted_contact/
      Handler: app.lambda_handler
      FunctionName: lambda-trusted-contact-microservice-mvp
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LambdaDynamo-lambda-trusted-contact-mvp"
      Environment:
        Variables:
          REGION: eu-south-1
          DMS_TABLE: dead_man_switch_settings_mvp
          TRUSTED_CONTACT_TABLE: trusted_contacts_mvp
          SOURCE_EMAIL: swe.bitbybit@gmail.com
      Events:
        PostDmsSettings:
          Type: HttpApi
          Properties:
            Path: /dms_settings
            Method: post
            ApiId: !Ref AppHttpApi
            Auth:
              Authorizer: MyJWTAuthorizer
        GetDmsSettings:
          Type: HttpApi
          Properties:
            Path: /dms_settings
            Method: get
            ApiId: !Ref AppHttpApi
            Auth:
              Authorizer: MyJWTAuthorizer
        PutHeartBeat:
          Type: HttpApi
          Properties:
            Path: /dms_settings/heartbeat
            Method: put
            ApiId: !Ref AppHttpApi
            Auth:
              Authorizer: MyJWTAuthorizer
        PutDmsSettings:
          Type: HttpApi
          Properties:
            Path: /dms_settings
            Method: put
            ApiId: !Ref AppHttpApi
            Auth:
              Authorizer: MyJWTAuthorizer
        PostTrustedContact:
          Type: HttpApi
          Properties:
            Path: /trusted_contact
            Method: post
            ApiId: !Ref AppHttpApi
            Auth:
              Authorizer: MyJWTAuthorizer
        PutTrustedContact:
          Type: HttpApi
          Properties:
            Path: /trusted_contact/{contact_id}
            Method: put
            ApiId: !Ref AppHttpApi
            Auth:
              Authorizer: MyJWTAuthorizer
        GetTrustedContacts:
          Type: HttpApi
          Properties:
            Path: /trusted_contact
            Method: get
            ApiId: !Ref AppHttpApi
            Auth:
              Authorizer: MyJWTAuthorizer
        GetTrustedContact:
          Type: HttpApi
          Properties:
            Path: /trusted_contact/{contact_id}
            Method: get
            ApiId: !Ref AppHttpApi
            Auth:
              Authorizer: MyJWTAuthorizer
        DeleteTrustedContact:
          Type: HttpApi
          Properties:
            Path: /trusted_contact/{contact_id}
            Method: delete
            ApiId: !Ref AppHttpApi
            Auth:
              Authorizer: MyJWTAuthorizer
        PutAlert:
          Type: HttpApi
          Properties:
            Path: /alert
            Method: put
            ApiId: !Ref AppHttpApi
            Auth:
              Authorizer: MyJWTAuthorizer
      
  TrustedContactsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Delete
    Properties:
      TableName: trusted_contacts_mvp
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: contact_id
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: contact_id
          AttributeType: S
      SSESpecification:
        SSEEnabled: true
  
  DeadManSwitchSettingsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Delete
    Properties:
      TableName: dead_man_switch_settings_mvp
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
      SSESpecification:
        SSEEnabled: true

Outputs:  
  DiaryFunction:
    Description: Trusted contacts lambda function ARN
    Value: !GetAtt DiaryFunction.Arn
  
  TrustedContactFunction:
    Description: Diary notes lambda function ARN
    Value: !GetAtt TrustedContactFunction.Arn

  TrustedContactsTable:
    Description: Trusted Contact DynamoDB Table Name
    Value: !Ref TrustedContactsTable
  
  DeadManSwitchSettingsTable:
    Description: Dead Man switch DynamoDB Table Name
    Value: !Ref DeadManSwitchSettingsTable
